# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vismaily <nenie_iri@mail.ru>               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/26 12:58:47 by vismaily          #+#    #+#              #
#    Updated: 2023/01/05 17:39:29 by vismaily         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3"

services:
    mariadb:
        build: ./requirements/mariadb/
        image: mariadb
        container_name: c_mariadb
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
    wordpress:
        build:
            context: ./requirements/wordpress/
            args:
                - MYSQL_HOST=mariadb
        image: wordpress
        container_name: c_wordpress
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress_data:/var/www/wordpress/
        restart: on-failure
        depends_on:
            - mariadb
    nginx:
        build:
            context: ./requirements/nginx/
            args:
                - WORDPRESS_HOST=wordpress
        image: nginx
        container_name: c_nginx
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress_data:/var/www/wordpress/
        restart: on-failure
        ports:
            - "443:443"
        depends_on:
            - wordpress

networks:
    inception:

volumes:
    wordpress_data:
        driver_opts:
            device: $HOME/data/mariadb
            o: bind
            type: none
    db_data:
        driver_opts:
            device: $HOME/data/mariadb
            o: bind
            type: none
